/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import BaseDatos.ConexionFavoritos;
import Dominio.mdFavoritos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */
public class Favoritos extends javax.swing.JFrame {

    /**
     * Creates new form Favoritos
     */
    public Favoritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFavoritos = new javax.swing.JTable();
        jButtonBusFav = new javax.swing.JButton();
        jButtonFav = new javax.swing.JButton();
        jTextFieldBuscarFav = new javax.swing.JTextField();
        jTextFieldCO = new javax.swing.JTextField();
        jTextFieldNO = new javax.swing.JTextField();
        LbPoke = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableFavoritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFavoritos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, 160));

        jButtonBusFav.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jButtonBusFav.setText("Busqueda");
        jButtonBusFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusFavActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBusFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jButtonFav.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jButtonFav.setText("Favoritos");
        jButtonFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 43));
        getContentPane().add(jTextFieldBuscarFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 126, -1));
        getContentPane().add(jTextFieldCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 174, -1));
        getContentPane().add(jTextFieldNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 140, -1));

        LbPoke.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\pokemon-go-evolucionar.jpg")); // NOI18N
        getContentPane().add(LbPoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 720, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String b;
    String tab[][];  
    String nom;
    String cor;
    
    private void jButtonBusFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusFavActionPerformed
        ConexionFavoritos confav = new ConexionFavoritos();     
        b = jTextFieldBuscarFav.getText();
        List<mdFavoritos> E = confav.BusquedaEntrenador(b.toUpperCase());
        if (E==null||E.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Ingresa el dato correcto");
        }else{
            for (mdFavoritos EC : E) {
               nom = EC.getEntrenador();
               cor = EC.getCorreo();
            }
            jTextFieldNO.setText(nom);
            jTextFieldCO.setText(cor);
        }
    }//GEN-LAST:event_jButtonBusFavActionPerformed

    private void jButtonFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavActionPerformed
        ConexionFavoritos confav = new ConexionFavoritos();
        String encabezado []={"Id","Id_Poke","Nombre","Entrenador","Correo"};
        List<mdFavoritos> P = confav.SeleccionarTodo();
        tab = new String[P.size()][5];
        int acumulador=0;
        for (mdFavoritos fav : P) {
            tab[acumulador][0]=fav.getNumero();
            tab[acumulador][1]=fav.getCorrelativo();
            tab[acumulador][2]=fav.getNombre();
            tab[acumulador][3]=fav.getEntrenador();
            tab[acumulador][4]=fav.getCorreo();
            acumulador++;
            jTableFavoritos.setModel(new DefaultTableModel(tab,encabezado));
        }
    }//GEN-LAST:event_jButtonFavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Favoritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbPoke;
    private javax.swing.JButton jButtonBusFav;
    private javax.swing.JButton jButtonFav;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFavoritos;
    private javax.swing.JTextField jTextFieldBuscarFav;
    private javax.swing.JTextField jTextFieldCO;
    private javax.swing.JTextField jTextFieldNO;
    // End of variables declaration//GEN-END:variables
}
